[project]
authors = ["Dan Allan <dallan@bnl.gov>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "interactive-tutorial-demo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.5,<4"

[pypi-dependencies]
sphinx = ">=8.0.2, <9"
myst-nb = ">=1.1.1, <2"
jupytext = ">=1.16.4, <2"
sphinx-book-theme = ">=1.1.3, <2"
