---
name: Publish

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 * * 1'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    name: Publish HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Build executed notebooks and HTML
        run: pixi run build

      - name: Upload HTML as GitHub artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
