---
name: Publish

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 * * 1'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    name: Publish HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Build executed notebooks and HTML
        run: pixi run build

      - name: Upload HTML as GitHub artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/html

      - name: Upload executed notebooks as GitHub artifact
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebooks
          path: build/jupyter_execute/recipes

  deploy-gh-pages:
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy HTML to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-notebooks:
    # Sets permissions of the GITHUB_TOKEN to allow pushing to 'notebooks' branch
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download executed notebooks from 'build' job
        uses: actions/download-artifact@v4
        with:
          name: executed-notebooks
          path: notebooks

      - run: ls .
      - run: ls ..
      - run: tree .
      - run: git remote -v

      - name: Publish executed notebooks to 'notebooks' branch of this repo
        run: |
          git checkout -B notebooks
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add notebooks
          git commit -m "generated"
          git push origin notebooks --force
