---
name: Publish HTML

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  publish:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    name: Publish HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.1

      - name: Build executed notebooks and HTML
        run: pixi build

      - name: Publish
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847  # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html/
          commit_message: ${{ github.event.head_commit.message }}
